name: react project

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  DELIVERY:
    name: Push para dockerHub
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            username: ${{ secrets.USER  }}
            password: ${{ secrets.PASSWD  }}

        - name: Extract Medatada
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: reginaabarbara/react_project
        
        - name: Build and push Docker images
          uses: docker/build-push-action@v6.9.0
          with:
            push: true
            context: .
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{  steps.meta.outputs.labels  }}
